window.PROJECTS = [
  {
    id: 'vk-video',
    title: 'VK Видео',
    year: '2024',
    images: [],
    video: null,
    videos: [
      'assets/project_1/video_1.mp4',
      'assets/project_1/video_2.mp4',
    ],
    goal: 'Рассказать о запуске раздела VK Видео Детям.',
    idea: 'VK Видео Детям — территория только для детей. Взрослым не входить! По аналогии с тем, как дети захватили целый раздел внутри VK Видео, так и в коммуникации они захватывали всё вокруг: телеграм-паблики заговорили детским языком, офис VK покрылся AR-каракулями, во взрослых шоу появились дисклеймеры «такого нет в VK Видео Детям», а в вирусных скетчах для тик-тока они и вовсе оказались в мире без взрослых.',
    result: 'После этой рекламной кампании VK Видео стало лидером по спонтанному знанию среди видеосервисов в категории детского контента.',
    role: 'Поиск инсайтов, разработка big idea, сценария, спецпроектов, креативное супервизирование и упаковка всех материалов кампании.',
  },
  {
    id: 'project-2',
    title: 'Название проекта',
    year: '2024',
    images: [
      'assets/project_2/image_1.jpg',
      'assets/project_2/image_2.jpg',
    ],
    video: null,
    videos: [
      'assets/project_2/video_1.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-3',
    title: 'Название проекта',
    year: '2023',
    images: [],
    video: null,
    videos: [
      'assets/project_3/video_1.mp4',
      'assets/project_3/video_2.mp4',
      'assets/project_3/video_3.mp4',
      'assets/project_3/video_4.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-4',
    title: 'Название проекта',
    year: '2023',
    images: [
      'assets/project_4/image_1.jpg',
      'assets/project_4/image_2.jpg',
      'assets/project_4/image_3.jpg',
      'assets/project_4/image_4.jpg',
    ],
    video: null,
    videos: [
      'assets/project_4/video_1.mp4',
      'assets/project_4/video_2.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-5',
    title: 'Название проекта',
    year: '2022',
    images: [],
    video: null,
    videos: [
      'assets/project_5/video_1.mp4',
      'assets/project_5/video_2.mp4',
      'assets/project_5/video_3.mp4',
      'assets/project_5/video_4.mp4',
      'assets/project_5/video_5.mp4',
      'assets/project_5/video_6.mp4',
      'assets/project_5/video_7.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-6',
    title: 'Название проекта',
    year: '2022',
    images: [
      'assets/project_6/image_1.jpg',
    ],
    video: null,
    videos: [
      'assets/project_6/video_1.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-7',
    title: 'Название проекта',
    year: '2022',
    images: [],
    video: null,
    videos: [
      'assets/project_7/video_1.mp4',
      'assets/project_7/video_2.mp4',
      'assets/project_7/video_3.mp4',
      'assets/project_7/video_4.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-8',
    title: 'Название проекта',
    year: '2022',
    images: [
      'assets/project_8/image_1.jpg',
      'assets/project_8/image_2.jpg',
    ],
    video: null,
    videos: [
      'assets/project_8/video_1.mp4',
      'assets/project_8/video_2.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-9',
    title: 'Название проекта',
    year: '2022',
    images: [],
    video: null,
    videos: [
      'assets/project_9/video_1.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-10',
    title: 'Название проекта',
    year: '2022',
    images: [
      'assets/project_10/image_1.jpg',
    ],
    video: null,
    videos: [
      'assets/project_10/video_1.mp4',
      'assets/project_10/video_2.mp4',
      'assets/project_10/video_3.mp4',
      'assets/project_10/video_4.mp4',
      'assets/project_10/video_5.mp4',
      'assets/project_10/video_6.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-11',
    title: 'Название проекта',
    year: '2022',
    images: [
      'assets/project_11/image_1.jpg',
      'assets/project_11/image_2.jpg',
    ],
    video: null,
    videos: [
      'assets/project_11/video_1.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-12',
    title: 'Название проекта',
    year: '2022',
    images: [],
    video: null,
    videos: [
      'assets/project_12/video_1.mp4',
      'assets/project_12/video_2.mp4',
      'assets/project_12/video_3.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-13',
    title: 'Название проекта',
    year: '2022',
    images: [],
    video: null,
    videos: [
      'assets/project_13/video_1.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
];
