window.PROJECTS = [
  {
    id: 'vk-video',
    title: 'VK Видео Детям',
    year: '2024',
    images: [],
    video: null,
    videos: [
      'assets/project_1/video_1.mp4',
      'assets/project_1/video_2.mp4',
    ],
    goal: 'Рассказать о запуске раздела VK Видео Детям.',
    idea: 'VK Видео Детям — территория только для детей. Взрослым не входить!',
    execution: 'Запустили масштабную кампанию: ролик, DOOH, спецпроекты в digital и офлайн. Телеграм-каналы вышли с новостями на детском языке, в TikTok разлетелись вирусные скетчи о мире без взрослых, сделанные в Sora. Офис VK разукрасили AR-каракулями, а в шоу появились дисклеймеры «такого нет в VK Видео Детям». Блогерам-мамам отправили релакс-боксы, где каждый подарок был рассчитан на количество минут в детском плейлисте.',
    result: 'После этой рекламной кампании VK Видео стало лидером по спонтанному знанию среди видеосервисов в категории детского контента.',
    role: 'Поиск инсайтов, разработка big idea, OLV, спецпроектов, креативное супервизирование (тексты, брифы, сценарии) и упаковка всех материалов кампании.',
  },
  {
    id: 'project-2',
    title: 'Ого-го-облако',
    year: '2024',
    images: [],
    video: null,
    videos: [
      'assets/project_2/video_1.mp4',
      'assets/project_2/video_2.mp4',
      'assets/project_2/video_3.mp4',
      'assets/project_2/video_4.mp4',
    ],
    goal: 'Нестандартно рассказать о безлимитной автозагрузке для фото и видео в Облаке Mail.',
    idea: 'Ого-го-облако увеличит память твоего телефона до бесконечности.',
    execution: 'Выпустили ролик с бесконечно растущим телефоном и ролик на Гидропроект. Поставили стойки в ТЦ с обещанием увеличить память телефона и запустили про них посевы в телеграме. Сделали кликбейтные баннеры в стиле нулевых, вклинились в пиратские фильмы — заменили заставку Universal на Ого-го-облако и нативно встроились в контент. Разработали кликер, который «увеличивает» память телефона, и посеяли пост с длинным телефоном в пабликах.',
    result: 'TBA',
    role: 'Разработка big idea, спецпроектов, креативное супервизирование и упаковка всех материалов кампании — от ролика и баннеров до посевов в тг.',
  },
  {
    id: 'project-3',
    title: 'VK Видео глазки DIY',
    year: '2024',
    images: [
      'assets/project_3/image_1.jpg',
      'assets/project_3/image_2.jpg',
      'assets/project_3/image_3.jpg',
      'assets/project_3/image_4.jpg',
    ],
    video: null,
    videos: [
      'assets/project_3/video_1.mp4',
      'assets/project_3/video_2.mp4',
      'assets/project_3/video_3.mp4',
      'assets/project_3/video_4.mp4',
      'assets/project_3/video_5.mp4',
      'assets/project_3/video_6.mp4',
      'assets/project_3/video_7.mp4',
    ],
    goal: 'Рассказать о DIY-контенте в VK Видео.',
    idea: 'Смотри, как надо — серия вирусных скетчей с маскотами VK Видео.',
    execution: 'Семь скетчей на популярные DIY-темы: авто, еда, бьюти, техника, технологии, спорт.',
    result: 'TBA',
    role: 'Сценарии, креативное супервизирование и упаковка всех материалов кампании.',
  },
  {
    id: 'project-6',
    title: 'Название проекта',
    year: '2022',
    images: [
      'assets/project_6/image_1.jpg',
    ],
    video: null,
    videos: [
      'assets/project_6/video_1.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-7',
    title: 'Название проекта',
    year: '2022',
    images: [],
    video: null,
    videos: [
      'assets/project_7/video_1.mp4',
      'assets/project_7/video_2.mp4',
      'assets/project_7/video_3.mp4',
      'assets/project_7/video_4.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-8',
    title: 'Название проекта',
    year: '2022',
    images: [
      'assets/project_8/image_1.jpg',
      'assets/project_8/image_2.jpg',
    ],
    video: null,
    videos: [
      'assets/project_8/video_1.mp4',
      'assets/project_8/video_2.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-9',
    title: 'Название проекта',
    year: '2022',
    images: [],
    video: null,
    videos: [
      'assets/project_9/video_1.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-10',
    title: 'Название проекта',
    year: '2022',
    images: [
      'assets/project_10/image_1.jpg',
    ],
    video: null,
    videos: [
      'assets/project_10/video_1.mp4',
      'assets/project_10/video_2.mp4',
      'assets/project_10/video_3.mp4',
      'assets/project_10/video_4.mp4',
      'assets/project_10/video_5.mp4',
      'assets/project_10/video_6.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-11',
    title: 'Название проекта',
    year: '2022',
    images: [
      'assets/project_11/image_1.jpg',
      'assets/project_11/image_2.jpg',
    ],
    video: null,
    videos: [
      'assets/project_11/video_1.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-12',
    title: 'Название проекта',
    year: '2022',
    images: [],
    video: null,
    videos: [
      'assets/project_12/video_1.mp4',
      'assets/project_12/video_2.mp4',
      'assets/project_12/video_3.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-13',
    title: 'Название проекта',
    year: '2022',
    images: [],
    video: null,
    videos: [
      'assets/project_13/video_1.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
];
