window.PROJECTS = [
  {
    id: 'vk-video',
    title: 'VK Видео',
    year: '2024',
    images: [],
    video: null,
    videos: [
      'assets/project_1/video_1.mp4',
      'assets/project_1/video_2.mp4',
    ],
    goal: 'Подчеркнуть уникальность VK Видео как универсального сервиса, в котором можно найти любые виды контента, любых российских блогеров в удобном формате отдельного приложения.',
    idea: 'Если мы утверждаем, что у нас есть «всё и все», значит, мы можем почелленджить сервис. Поэтому герои ролика из раза в раз задаются вопросом «Даже [...] есть в VK Видео?» и получают на него ответ, позволяющий нестандартно заявить контент.',
    result: 'Уже в первые дни рекламной кампании установки приложения превысили 100 000.',
    role: 'Креатив, сценарий, подготовка аниматика, разработка KV совместно с дизайнерами, участие на всех этапах продакшена, адаптация материалов для разных форматов.',
  },
  {
    id: 'project-2',
    title: 'Название проекта',
    year: '2024',
    images: [
      'assets/project_2/image_1.jpg',
      'assets/project_2/image_2.jpg',
    ],
    video: null,
    videos: [
      'assets/project_2/video_1.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-3',
    title: 'Название проекта',
    year: '2023',
    images: [],
    video: null,
    videos: [
      'assets/project_3/video_1.mp4',
      'assets/project_3/video_2.mp4',
      'assets/project_3/video_3.mp4',
      'assets/project_3/video_4.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-4',
    title: 'Название проекта',
    year: '2023',
    images: [
      'assets/project_4/image_1.jpg',
      'assets/project_4/image_2.jpg',
      'assets/project_4/image_3.jpg',
      'assets/project_4/image_4.jpg',
    ],
    video: null,
    videos: [
      'assets/project_4/video_1.mp4',
      'assets/project_4/video_2.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-5',
    title: 'Название проекта',
    year: '2022',
    images: [],
    video: null,
    videos: [
      'assets/project_5/video_1.mp4',
      'assets/project_5/video_2.mp4',
      'assets/project_5/video_3.mp4',
      'assets/project_5/video_4.mp4',
      'assets/project_5/video_5.mp4',
      'assets/project_5/video_6.mp4',
      'assets/project_5/video_7.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-6',
    title: 'Название проекта',
    year: '2022',
    images: [
      'assets/project_6/image_1.jpg',
    ],
    video: null,
    videos: [
      'assets/project_6/video_1.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-7',
    title: 'Название проекта',
    year: '2022',
    images: [],
    video: null,
    videos: [
      'assets/project_7/video_1.mp4',
      'assets/project_7/video_2.mp4',
      'assets/project_7/video_3.mp4',
      'assets/project_7/video_4.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-8',
    title: 'Название проекта',
    year: '2022',
    images: [
      'assets/project_8/image_1.jpg',
      'assets/project_8/image_2.jpg',
    ],
    video: null,
    videos: [
      'assets/project_8/video_1.mp4',
      'assets/project_8/video_2.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-9',
    title: 'Название проекта',
    year: '2022',
    images: [],
    video: null,
    videos: [
      'assets/project_9/video_1.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-10',
    title: 'Название проекта',
    year: '2022',
    images: [
      'assets/project_10/image_1.jpg',
    ],
    video: null,
    videos: [
      'assets/project_10/video_1.mp4',
      'assets/project_10/video_2.mp4',
      'assets/project_10/video_3.mp4',
      'assets/project_10/video_4.mp4',
      'assets/project_10/video_5.mp4',
      'assets/project_10/video_6.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-11',
    title: 'Название проекта',
    year: '2022',
    images: [
      'assets/project_11/image_1.jpg',
      'assets/project_11/image_2.jpg',
    ],
    video: null,
    videos: [
      'assets/project_11/video_1.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-12',
    title: 'Название проекта',
    year: '2022',
    images: [],
    video: null,
    videos: [
      'assets/project_12/video_1.mp4',
      'assets/project_12/video_2.mp4',
      'assets/project_12/video_3.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
  {
    id: 'project-13',
    title: 'Название проекта',
    year: '2022',
    images: [],
    video: null,
    videos: [
      'assets/project_13/video_1.mp4',
    ],
    goal: 'Опишите задачу.',
    idea: 'Опишите идею.',
    result: 'Опишите результаты.',
    role: 'Ваша роль.',
  },
];
